name: Continuos Integration

on: [pull_request, push]

jobs: 
  continuos-integration: 
    runs-on: windows-latest

    step: 
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 21.x
      - name: run install, build and test
        run: |
          npm run build
          npm run test